### ISSUE TITLE
Todo: resolve known bugs + features

### ISSUE THREAD

**Issue by edshen17** [edshen17/jishoBot#3]
##TODO:

* [x] !translate error when user inputs no arguments
* [x] !help function for embedding error codes in Discord
* [x] Separate code so it's more private using config.json
* [x] !define error with reading (outputs undefined if word is kana)
* [x] Format output of !define and !translate functions with embeds
* [x] Testing using Chai/Mocha
